### ISSUE TITLE
[ feature request ]  support assistant api

### ISSUE THREAD

**Issue by zhaolun7** [Azure-Samples/azure-openai-chat-frontend#31]
Does this project have plans to support assistant api?
https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/assistant

**Comment by anfibiacreativa** [comment]
Hi @zhaolun7 . This project does not plan to support assistant API in the future. But you have a template supporting assustant here https://github.com/Azure-Samples/azure-openai-assistant-javascript
